version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: 
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Install Docker client and pip
          command: |
            sudo apt-get update
            sudo apt-get install python3.7
            sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get install docker-ce docker-ce-cli containerd.io
            sudo apt-get install python3-pip
      - run:
          name: Install dependencies
          command: |
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            python test.py 
      - run:
          name: Build and push Docker image
          command: |
            docker build -t sw9719/circleciflask:latest .
            echo "Mepro@mw3" | docker login -u sw9719 --password-stdin
            docker push sw9719/circleciflask:latest