version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: 
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Install Docker client and pip
          command: |
            apk add python3
            apk add py-pip
      - run:
          name: Install Dependencies
          command: |
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            python3 test.py 
      - run:
          name: Build and push Docker image
          command: |

            docker build -t sw9719/circleciflask:latest .
            echo "Mepro@mw3" | docker login -u sw9719 --password-stdin
            docker push sw9719/circleciflask:latest