version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: 
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install python and pip
          command: |
            apk add --no-cache python3
            apk add --no-cache py3-pip
      - run:
          name: Install Dependencies
          command: |
            pip3 install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            python3 test.py 
      - run:
          name: Build and push Docker image
          command: |
            docker build -t <image name> .
            docker login --username=<your username> --password=<your password>
            docker push <image name with tag>
            sh deploy.sh